import { OperatorList } from '../common.types';

export const OperatorGroupNamesList = [
  'creation',
  'join creation',
  'transformation',
  'filtering',
  'join',
  'multicasting',
  'error handling',
] as const;

export const operatorsNames: OperatorList = {
  creation: [
    'interval',
    'from',
    'fromEvent',
    'of',
    'range',
    'timer',
    'defer',
    'throwError',
  ],
  join: [
    'combineLatestAll',
    'concatAll',
    'exhaustAll',
    'mergeAll',
    'switchAll',
    'startWith',
    'withLatestFrom',
  ],
  'error handling': ['catchError', 'retry', 'retryWhen'],
  'join creation': [
    'combineLatest',
    'concat',
    'forkJoin',
    'merge',
    'partition',
    'race',
    'zip',
  ],
  filtering: [
    'audit',
    'auditTime',
    'debounce',
    'debounceTime',
    'distinct',
    'distinctUntilChanged',
    'distinctUntilKeyChanged',
    'elementAt',
    'filter',
    'first',
    'ignoreElements',
    'last',
    'sample',
    'sampleTime',
    'single',
    'skip',
    'skipLast',
    'skipUntil',
    'skipWhile',
    'take',
    'takeLast',
    'takeUntil',
    'takeWhile',
    'throttle',
    'throttleTime',
  ],
  multicasting: [
    'multicast',
    'publish',
    'publishBehavior',
    'publishLast',
    'publishReplay',
    'share',
  ],
  transformation: [
    'buffer',
    'bufferCount',
    'bufferTime',
    'bufferToggle',
    'bufferWhen',
    'concatMap',
    'concatMapTo',
    'exhaust',
    'exhaustMap',
    'expand',
    'groupBy',
    'map',
    'mapTo',
    'mergeMap',
    'mergeMapTo',
    'mergeScan',
    'pairwise',
    'partition',
    'pluck',
    'scan',
    'switchScan',
    'switchMap',
    'switchMapTo',
    'window',
    'windowCount',
    'windowTime',
    'windowToggle',
    'windowWhen',
  ],
};
